export const TIPOS_EXAMES = [
  "Ácido Úrico",
  "Creatinina",
  "Colesterol Total",
  "Colesterol HDL",
  "Colesterol LDL",
  "Covid-19",
  "Eletrocardiograma",
  "Ecocardiograma",
  "Endoscopia",
  "Glicemia",
  "Hemograma Completo",
  "Mamografia",
  "Papanicolau",
  "PSA",
  "Raio-X",
  "Ressonância Magnética",
  "Tomografia",
  "Triglicerídeos",
  "TSH",
  "T4 Livre",
  "Urina Tipo I",
  "Ureia",
  "Ultrassonografia",
  "Vitamina D",
  "Vitamina B12",
  "Outros",
];